### ISSUE TITLE
Merge back into upstream

### ISSUE THREAD

**Issue by rimas-kudelis** [HydraWiki/Tabber#9]
It would be great if changes from this repository were merged [upstream](https://phabricator.wikimedia.org/diffusion/ETBR/). I was recently upgrading a couple MediaWiki installations, and I missed the fact that currently Tabber lives in this repository, and checked out from Wikimedia's git instead, just because the repository was available there. Even though [the extension page](https://www.mediawiki.org/wiki/Extension:Tabber) points to this repository, not everyone will go and check during upgrade. Now that commits to this repository are relatively rare, the necessity for a fork here is even less obvious.

**Comment by SamanthaNguyen** [comment]
Filed upstream, https://phabricator.wikimedia.org/T157885, filed a patch too: https://gerrit.wikimedia.org/r/#/c/337246/

Please do feel free to subscribe to the ticket if you already have a Phabricator account; if you don't see, also check out [this useful guide](https://www.mediawiki.org/wiki/Special:MyLanguage/Phabricator/Help#Creating_your_account_and_notifications) too! And if you want to, you can add yourself as a CR (code reviewer) to the patch :-)

**Comment by rimas-kudelis** [comment]
Thanks @SamanthaNguyen!

**Comment by SamanthaNguyen** [comment]
@rimas-kudelis Sure! 

Currently according to the [Gerrit group for the Tabber extension](https://gerrit.wikimedia.org/r/#/admin/groups/229,members), only has 1 project owner with +2 rights which is Tim Weyer; his last commits were [over 2 years ago!](https://gerrit.wikimedia.org/r/#/q/owner:Tim+Weyer) Because of this, I'll try to contact a core developer (since they have [+2 rights](https://www.mediawiki.org/wiki/Gerrit/%2B2) on every repository) so the patch can be code reviewed and merged. 

Cheers!

**Comment by Alexia** [comment]
My apologies for being behind on Github issue tickets.  This is still an active project for us, but we do not have it up for a new iteration at the moment.

**Comment by SamanthaNguyen** [comment]
No worries! Also I'd like to point out that the patch has just been +2'd (and thus merged) - https://github.com/wikimedia/mediawiki-extensions-Tabber/commit/62f118fecd55082eb46fc820f8ea76125a49c5b8 Could any of you close this ticket? Thanks!
